cmake_minimum_required(VERSION 3.22)

set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86)

if(NOT DEFINED ENV{MINGW32_PREFIX})
    set(_MINGW32_DEFAULT_ROOT "C:/msys64/mingw32")
else()
    file(TO_CMAKE_PATH "$ENV{MINGW32_PREFIX}" _MINGW32_DEFAULT_ROOT)
endif()

if(NOT EXISTS "${_MINGW32_DEFAULT_ROOT}/bin/gcc.exe")
    message(FATAL_ERROR "Cannot find mingw32 toolchain under ${_MINGW32_DEFAULT_ROOT}. "
                        "Set MINGW32_PREFIX environment variable to your MinGW32 root.")
endif()

set(CMAKE_C_COMPILER "${_MINGW32_DEFAULT_ROOT}/bin/gcc.exe" CACHE FILEPATH "" FORCE)
set(CMAKE_CXX_COMPILER "${_MINGW32_DEFAULT_ROOT}/bin/g++.exe" CACHE FILEPATH "" FORCE)
set(CMAKE_RC_COMPILER "${_MINGW32_DEFAULT_ROOT}/bin/windres.exe" CACHE FILEPATH "" FORCE)

set(CMAKE_C_FLAGS_INIT "-m32")
set(CMAKE_CXX_FLAGS_INIT "-m32")

set(CMAKE_FIND_ROOT_PATH "${_MINGW32_DEFAULT_ROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
